apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
spec:
  ingressClassName: "nginx"
  rules:
    - host: {{ .Values.ingress.hostname }}
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: {{ .Release.Name }}
              port:
                number: {{ .Values.service.port }}

  tls:
    - hosts:
      - {{ .Values.ingress.hostname }}
      secretName: web-go4clouds-net-tls
